title: Meta
fields:
  -
    handle: title
    field:
      display: Title
      type: text
      always_save: false
      character_limit: 60
  -
    handle: description
    field:
      display: Description
      type: textarea
      always_save: false
      character_limit: '160'
  -
    handle: keywords
    field:
      type: taggable
      display: Keywords
  -
    handle: image
    field:
      container: assets
      max_files: 1
      display: Image
      type: assets
