<?php

namespace App\Redirects;

use Illuminate\Support\Facades\File;

/**
 * Addresses people asked for and did not get.
 *
 * The point of the log is the one-click move on the redirects screen: a 404
 * with a count beside it is a redirect somebody forgot to make. It is a tally,
 * not a history — one row per path, with how often and when last.
 *
 * Storage, not content: it is regenerated by traffic, differs per environment,
 * and must never travel in a deploy.
 */
class MissingLog
{
    /** Beyond this many distinct paths the thinnest ones are dropped. */
    protected const KEEP = 200;

    public function record(string $path): void
    {
        $rows = $this->all();
        $key = $path;

        $rows[$key] = [
            'hits' => (int) ($rows[$key]['hits'] ?? 0) + 1,
            'last_seen' => now()->toIso8601String(),
        ];

        if (count($rows) > static::KEEP) {
            uasort($rows, fn ($a, $b) => $b['hits'] <=> $a['hits']);
            $rows = array_slice($rows, 0, static::KEEP, true);
        }

        $this->write($rows);
    }

    /**
     * The log, busiest first, as rows the screen can draw.
     *
     * @return list<array{path: string, hits: int, last_seen: string}>
     */
    public function top(int $limit = 50): array
    {
        return collect($this->all())
            ->map(fn (array $row, string $path) => [
                'path' => $path,
                'hits' => (int) ($row['hits'] ?? 0),
                'last_seen' => (string) ($row['last_seen'] ?? ''),
            ])
            ->sortByDesc('hits')
            ->values()
            ->take($limit)
            ->all();
    }

    /** Drop one path — it has been answered, by a redirect or by a new page. */
    public function forget(string $path): void
    {
        $rows = $this->all();

        unset($rows[$path]);

        $this->write($rows);
    }

    public function clear(): void
    {
        $this->write([]);
    }

    /** @return array<string, array{hits: int, last_seen: string}> */
    protected function all(): array
    {
        $path = $this->path();

        if (! File::exists($path)) {
            return [];
        }

        $decoded = json_decode(File::get($path), true);

        return is_array($decoded['missing'] ?? null) ? $decoded['missing'] : [];
    }

    /** @param  array<string, array{hits: int, last_seen: string}>  $rows */
    protected function write(array $rows): void
    {
        $dir = dirname($this->path());

        if (! File::isDirectory($dir)) {
            File::makeDirectory($dir, 0755, true);
        }

        File::put($this->path(), json_encode(
            ['missing' => $rows],
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
        ));
    }

    public function path(): string
    {
        return storage_path('app/redirects/missing.json');
    }
}
