title: 'Block text settings'
# Importeres af settings-fanen i blocks/text.yaml.
# CSS-output til nye felter tilføjes ét sted:
# partials/blocks/text_settings_css.antlers.html
fields:
  -
    handle: main
    field:
      type: tab
      display: Main
      localizable: false
  -
    handle: text_alignment
    field:
      options:
        - key: left
          value: Left
        - key: center
          value: Center
        - key: right
          value: Right
      type: button_group
      display: 'Text alignment'
      localizable: false
  -
    handle: padding
    field:
      max: 12
      type: spacing
      display: Padding
      localizable: false
